menu:
  Uband: http://web.gambition.cn
  Blog: /
  Archives: /archives


# duoshuo comment
duoshuo: false
duoshuo_name:

# disqus comment
disqus: true
disqus_shortname: uband

# google analytics
googleTrackId:
